core.entity_form_display.group.blp_project.default:
  expected_config: { }
  update_actions:
    add:
      third_party_settings:
        field_group:
          group_settings:
            children:
              - field_flexible_group_visibility
